branches: ["main"]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: |
        find policies/ -type f \( -name '*.rego' ! -name '*_test.rego' \) -exec sed -i -e "s/#  version: .*/#  version: \"${nextRelease.version}\"/" {} \;
  - - "@semantic-release/git"
    - assets:
        - policies/*
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/github"
    - successComment: false
      failTitle: false
      failComment: false
      labels: ["automated"]