---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autogov-policy-library
  description: Dedicated Rego policy library for automated governance
  annotations:
    github.com/project-slug: liatrio/autogov-policy-library
  tags:
    - automated-governance
    - autogov
    - policy
    - rego
    - opa
spec:
  owner: "group:default/tag-autogov"
  lifecycle: in-progress
  type: library
