name: Build Bundle Composite Action

description: >-
  A composite action that is placed in ./.github/actions/build-image/action.yaml whereby
  ./.github/workflows/rw-<permissions_path>-attest-image.yaml will trigger this action to build an image. The steps
  can be adjusted per the users need just as long as the output is the image digest.

inputs:
  subject-name:
    description: The name for the image.
    required: true
    default: ghcr.io/${{ github.repository }}
  opa-version:
    description: The version of OPA to use.
    required: false
    default: "1.2.0"
outputs:
  image-digest:
    description: The image digest of the image that was built from the build-bundle job.
    value: ${{ steps.push-bundle.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Get Next Semantic Release Tag # premptively tags pushed/registry image w/ release tag
      id: semantic-release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
      with:
        dry: true
        allow-initial-development-versions: true
        github-token: ${{ github.token }}
    - name: Build Artifact Metadata
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
      with:
        sep-tags: ','
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          type=raw,value=${{ steps.semantic-release.outputs.version }},enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@b2b258e089860efaadaaf71bf6e3aecb4a3eeff1 # v2.4.0
      with:
        version: ${{ inputs.opa-version }}
    - name: Build OPA Bundle
      shell: bash
      id: build-bundle
      run: |
        opa \
          build \
          --bundle ./policies \
          --ignore "*_test.rego" \
          --output bundle.tar.gz
    - name: Get Hash of Bundle
      shell: bash
      id: hash
      run: echo "hash=$(sha256sum bundle.tar.gz | awk '{print "sha256:" $1}')" >> $GITHUB_OUTPUT
    - name: Create config.json with hash
      shell: bash
      run: |
        echo '{
          "rootfs": {
          "type": "layers",
          "diff_ids": [
            "${{ steps.hash.outputs.hash }}"
          ]
          }
        }' > config.json
    - name: Setup ORA
      uses: oras-project/setup-oras@38de303aac69abb66f3e6255b7198bff35f323e3 # v2.0.0
    - name: Oras push bundle
      shell: bash
      id: push-bundle
      run: |
        ORAS_PUSH_DIGEST=$(oras push \
            "ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags }}" \
            bundle.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip \
            --config config.json:application/vnd.oci.image.config.v1+json \
            --format json | jq -r '.digest')

        echo "digest=$ORAS_PUSH_DIGEST" >> $GITHUB_OUTPUT
