name: Build Bundle Composite Action

description: >-
  A composite action that is placed in ./.github/actions/build-blob/action.yaml whereby
  ./.github/workflows/rw-<permissions_path>-attest-blob.yaml will trigger this action to build the blob(s). The steps
  can be adjusted per the user's need just as long as the result blob file(s) is referenced for
  downstream jobs.

inputs:
  opa-version:
    description: The version of OPA to use.
    required: false
    default: "1.2.0"

runs:
  using: composite
  steps:
    - name: Get Next Semantic Release Tag # premptively tags pushed/registry image w/ release tag
      id: semantic-release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
      with:
        dry: true
        allow-initial-development-versions: true
        github-token: ${{ github.token }}
    - name: Check out repository code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 #v2.2.0
      with:
        version: ${{ inputs.opa-version }}
    - name: Build OPA Bundle and Create Schemas Archive
      shell: bash
      run: |
        opa \
          build \
          --bundle ./policies \
          --ignore "*_test.rego" \
          --output bundle.tar.gz
        tar -czf schemas.tar.gz -C schemas .
