name: Policy Library Workflow

on:
  workflow_dispatch:
  push:
    branches: ['**']
    paths-ignore:
      - .github/workflows/wf-slack-alert.yaml
      - README.md
      - catalog-info.yaml
      - renovate.json

env:
  OPA_VERSION: 0.67.1
  REGAL_VERSION: 0.28.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Regal
        uses: StyraInc/setup-regal@33a142b1189004e0f14bf42b15972c67eecce776 # v1.0
        with:
          version: ${{ env.REGAL_VERSION }}
      - name: Run Regal lint
        run: regal lint --format github ./policies

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 #v2.2.0
        with:
          version: ${{ env.OPA_VERSION }}
      - name: Run OPA Tests
        run: opa test -v -s ./schemas ./policies/
      - name: Check OPA Policies
        run: opa check --rego-v1 --v1-compatible -s schemas ./policies

  attest-image-hp: #image
    if: github.event.pull_request.draft == false
    needs: test
    permissions:
      id-token: write
      attestations: write
      packages: write
      contents: write
    uses: liatrio/liatrio-gh-autogov-workflows/.github/workflows/rw-hp-build-image.yaml@ecc12e03a3415b4343d31499a1e9b09e1c6273e2 # v0.2.3
    secrets: inherit
    with:
      subject-name: ghcr.io/${{ github.repository }}
      cert-identity: https://github.com/liatrio/liatrio-gh-autogov-workflows/.github/workflows/rw-hp-attest-image.yaml@ecc12e03a3415b4343d31499a1e9b09e1c6273e2 # v0.2.3
