on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'catalog-info.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.67.1
      - name: Run OPA Tests
        id: run-opa-tests
        run: opa test policy -v

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
      - name: Run OPA Tests
        run: opa test policy -v
      - name: Build OPA Bundle
        run: opa build --ignore "*_test.rego" policy
     - name: Run go-semantic-release
        uses: go-semantic-release/action@v1
        id: go-semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true